const Data = {
  menu: {
    search: {
      columOne: [
        {
          labe: 'Kategori',
          inputText: 'Personbil',
        },
        {
          labe: 'Drivmiddel',
          inputText: 'Alle',
        },
        {
          labe: 'Pristype',
          inputText: 'Alle',
        },
      ],
      columTwo: [
        {
          labe: 'Mærke',
          inputText: 'Mærke',
        },
        {
          labe: 'Km',
          inputText: 'fra',
        },
        {
          labe: 'Km',
          inputText: 'til',
        },
        {
          labe: 'Pris',
          inputText: 'fra',
        },
        {
          labe: 'Pris',
          inputText: 'til',
        },
      ],
      columThree: [
        {
          labe: '',
          inputText: '',
        },
        {
          labe: '',
          inputText: '',
        },
        {
          labe: '',
          inputText: '',
        },
      ],
    },
    checkboxes: ['Leasing', 'Ring for pris', 'Nysynet'],
  },
  cars: [
    {
      price: '224.900',
      decription: {
        name: 'Mazda 3',
        modelYear: 'modelår 2020',
        miles: '39.000 km',
      },
    },
    {
      price: '174.000 kr.',
      decription: {
        name: 'Mercedes Spring 316',
        modelYear: 'modelår 2017',
        miles: '116.000 km',
      },
    },
    {
      price: '574.900 kr.',
      decription: {
        name: 'Volvo XC60',
        modelYear: 'modelår 2019',
        miles: '51.000 km',
      },
    },
    {
      price: '22.900 kr.',
      decription: {
        name: 'Peaugeot',
        modelYear: 'modelår 2004',
        miles: '102.000 km',
      },
    },
    {
      price: '379.000 kr.',
      decription: {
        name: 'Ford Mustang',
        modelYear: 'modelår 2014',
        miles: '133.000 km',
      },
    },
    {
      price: '1.995 kr.',
      decription: {
        name: 'Suzuki Liana',
        modelYear: 'modelår 2009',
        miles: '185.000 km',
      },
    },
    {
      price: '114.800 kr.',
      decription: {
        name: 'Mercedes Citon 109',
        modelYear: 'modelår 2019',
        miles: '45.000 km',
      },
    },
    {
      price: '9.000 km',
      decription: {
        name: 'Mercedes Citan 109',
        modelYear: 'modelår 2021',
        miles: '9.000 km',
      },
    },
    {
      price: '399.900 kr.',
      decription: {
        name: 'Ford Kuga',
        modelYear: 'modelår 2022',
        miles: '9.000 km',
      },
    },
    {
      price: '379.800 kr.',
      decription: {
        name: 'Ford Kuga',
        modelYear: 'modelår 2021',
        miles: '14.000 km',
      },
    },
    {
      price: '2.585 kr.',
      decription: {
        name: 'Ford Transit Custom 370S',
        modelYear: 'modelår 2017',
        miles: '90.000 km',
      },
    },
    {
      price: '99.900 kr.',
      decription: {
        name: 'Renault Trafic T27',
        modelYear: 'modelår 2016',
        miles: '124.000 km',
      },
    },
  ],
  carsSecondSection: [
    [
      ['Audi', 'A1', 'A3', 'A4', 'A5', 'A6'],
      ['BMW', '318i', '320d', '320i', '520d', '530d'],
      ['Citroën', 'C1', 'C3', 'C3 Picasso', 'C4', 'C5'],
      ['Fiat', '500', '500L', 'Panda', 'Punto', 'Qubo'],
      ['Ford', 'Fiesta', 'Focus', 'Ka', 'Mondeo', 'S-MAX', ''],
      ['Hyudai', 'i10', 'i20', 'i30', 'i40', 'ix35'],
      ['Peaugeot', '107', '208', '308', '508', '3008'],
      ['Skoda', 'Citigo', 'Fabia', 'Octavia', 'Rapid', 'Superb'],
      ['Toyota', 'Aygo', 'Auris', 'Acensis', 'iW', 'Yaris'],
      ['VW', 'Golf VII', 'Passat', 'Polo', 'Touran', 'Up!'],
    ],
  ],
  usedCarsAllBrands: [
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bently',
    'BMW',
    'Cadilac',
    'Chevrolet',
    'Chrysler',
    'Citroën',
    'Daewoo',
    'Daihatsu',
    'Dodge',
    'Ferrari',
    'Fiat',
    'Ford',
    'Honda',
    'Hummer',
    'Hyundai',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lade',
    'Lamborghihi',
    'Land Rover',
    'Lexus',
    'Lotus',
    'Maseratti',
    'Mazda',
    'Mercedes',
    'MD',
    'Mini',
    'Mitsubashi',
    'Morris',
    'Nissan',
    'Opel',
    'Peugeot',
    'Pontiac',
    'Porsche',
    'Renault',
    'Rolls Royce',
    'Rover',
    'Saab',
    'Seat',
    'Skoda',
    'Smart',
    'Ssangyoung',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Volvo',
    'VW',
  ],
  allCategories: [
    'Brugte varebiler inkl. moms',
    'Brugte varebiler ekskl. moms',
    'Brugte autocampere',
    'Brugte busser',
    'Brugte lastbiler',
  ],
  allRegions: [
    'København',
    'Syd- og Vestsjælland',
    'Nordsjælland',
    'Bornhold',
    'Lolland-Falster',
    'Fyn',
    'Syd- og Sønderjylland',
    'Vestjylland',
    'Nordjylland',
    'Østjylland',
  ],
  cheapUsedCars:
    'Bilbasen er Danmarks største markedsplads for nye og brugte biler, autocampere, varevogne og busser. Her finder du et stort udvalg af alt fra billige brugte biler til fabriksnye modeller. Skal du sælge, giver Bilbasen dig også et overblik over, hvad din bil er værd.',
  footerAndMenu: {
    columnOne: [
      'Sælg bil',
      'Søg din bil',
      'Gerantisalg via Solgt.com',
      'Hvad er min bil værd',
      'Salgsguide',
    ],
    columnTwo: [
      'Køb bil',
      'Find en forhandler',
      'bilgafinansiering',
      'Nummerpladetjek',
      'Købsguide',
    ],
    columnThree: [
      'Snka om biler',
      'Fourm',
      'Brugeranmeldelser',
      'Bilbasens blog',
    ],
    columnFore: [
      'Min bilbase',
      'Mine annoncer',
      'Favoritter',
      'eamte søgninger',
    ],
    columnFire: [
      'Om bilsbasen',
      'Presse',
      'Brugervilkår',
      'Persondatapolitik',
      'Cookieindstillinger',
      'Bannerannoncering',
      'Sikkerhedsguide',
      'Hjælp',
    ],
  },
}
